added homework8
TDaniel07/Daniel-java-homework-repo pull request #4
Opened 2024-09-05 10:47 UTC by TDaniel07

2024-09-05 10:51 UTC, TDaniel07 commented
La ex10 am avut cateva dileme de cat de mult sa impart codul in asa fel incat sa se repete cat mai putin. Sunt parti din cod care sunt putin repetitive din cauza fapului ca pe acelasi arrayList trebuie sa gasesc un element si apoi sa fac o operatie diferita pe el. Am considerat sa sparg functiile si mai mult decat sunt acum dar m-am gandit ca se fragmenteaza si mai mult. Astept parerea ta cum ar fi fost mai ok

2024-09-05 19:56 UTC, urica requested changes
Super sir! Am lasat cateva comment!

2024-09-05 19:56 UTC, urica commented on homework8/src/Ex9.java
> +        System.out.println("Decimal number: " + Integer.parseInt(binaryNumber, 2));
inputScanner.close();

2024-09-05 19:56 UTC, urica commented on homework8/src/Ex10.java
> +        }
inputScanner.close(); ??

2024-09-05 19:56 UTC, urica commented on homework8/src/Ex10.java
> +    }
cumva aici ma sacaie faptul ca metodele sunt indentice doar actiunea este diferita si sunt destul de lungi. as mai scoate ceva cod comun intr-o alta metoda. am o idee dar te las pe tine sa gasesti o solutie.

2024-09-07 10:50 UTC, TDaniel07 commented
am creat o noua metoda care gaseste index-ul unui entry din diary pe baza date-ului. In rest am analizat codul si restul conditiilor care se se repeta duc la incetarea metodei. Acum sincer nu vad cum poate fi facut mai DRY, dar sunt mereu dornic sa invat si astept feedback :)

2024-09-07 10:54 UTC, TDaniel07 commented
As avea si un alt lucru de mentionat, in acest cod nu a fost respectat prea bine principiul Seperation of Concerncs deoarece acele functii nu mai ca se ocupa cu edit/delete/add dar se ocupa si cu relatarea informatiilor user-ului. Initial as fi vrut sa fac in asa fel incat functiile respective doar sa arunce erori in cazul in care datele furnizate nu sunt in regula dar avand in vedere ca nu am facut inca error management in Java am decis sa astept.
Am vazut ca error managementul in Java e destul de similar cu C++ dar poate ca bunele practici sunt diferite asa ca mai bine astept sa facem intai la curs.

2024-09-08 08:49 UTC, urica approved these changes

2024-09-08 08:49 UTC, urica commented on homework8/src/Ex10.java
> +    private int findDiaryEntry(LocalDate entryDate){
cool. asta vroiam!!! Esti bingo!

2024-09-08 12:14 UTC, merged